services:
  server:
    image: node:10.16-alpine
    container_name: api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    volumes:
      - ./apps/reddit-clone-api:/usr/src/app/reddit-clone-api
    working_dir: /usr/src/app/reddit-clone-api
    links:
      - mongodb
    command: npm run serve
      
  client:
    image: node:10.16-alpine
    container_name: front
    expose:
      - '3000'
    volumes:
      - ./apps/reddit-clone-front:/usr/src/app/reddit-clone-front
    working_dir: /usr/src/app/reddit-clone-front
    ports:
      - '3000:3000'
    command: npm start

  mongodb:
    hostname: mongo
    container_name: db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=reddit
    ports:
      - '27017:27017'
    # volumes:
    #   - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
